config_auto_export.settings:
  title: 'Configuration automatic export'
  route_name: config_auto_export.settings
  description: 'Configure directory, webhoook and delay for automatic exports of configurations'
  parent: system.admin_config_development
