config_auto_export.settings:
  path: '/admin/config/development/config_auto_export'
  defaults:
    _form: '\Drupal\config_auto_export\Form\Settings'
    _title: 'Configuration automatic export'
  requirements:
    _permission: 'administer site configuration'
  options:
    _admin_route: TRUE
